# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='predefined_means',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
